name: Subsplit

on: push

jobs:
  subsplit:
    runs-on: ubuntu-latest
    name: Split repositories
    steps:
      - name: Checkout history
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Split demo theme
        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/subsplit/git-subsplit.sh publish --debug --path="${GITHUB_WORKSPACE}" --heads="${${GITHUB_REF}/refs\/heads\//}" --no-tags themes/demo:https://bennothommo:${{ secrets.MAINTENANCE_TOKEN }}@github.com:octoberrain/demo-theme.git
